const express = require("express");
const { createClient } = require("@supabase/supabase-js");
const cors = require("cors");
require("dotenv").config();
const app = express();
app.use(express.json());
app.use(cors());
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);
function generateOTP() { return Math.floor(100000 + Math.random() * 900000).toString(); }
function generateTxnId() { return "TXN_" + Date.now() + "_" + Math.random().toString(36).substr(2, 9); }
async function logAction(action, userPhone, details) { await supabase.from("logs").insert({ action, user_phone: userPhone, details }); }
app.get("/health", (req, res) => res.json({ status: "API is running" }));
app.post("/initiate-transfer", async (req, res) => { try { const { sender_phone, receiver_phone, amount } = req.body; if (!sender_phone || !receiver_phone || !amount) return res.status(400).json({ error: "Missing fields" }); if (amount <= 0 || amount > 10000) return res.status(400).json({ error: "Invalid amount" }); const txn_id = generateTxnId(); const otp_code = generateOTP(); await supabase.from("transactions").insert({ txn_id, sender_phone, receiver_phone, amount, method: "atm_withdrawal", status: "otp_sent" }); await supabase.from("otps").insert({ txn_id, code: otp_code, expiry: new Date(Date.now() + 2 * 60 * 60 * 1000) }); await logAction("initiated_transfer", sender_phone, { txn_id, receiver_phone, amount }); await logAction("generated_otp", sender_phone, { txn_id, code: otp_code }); res.json({ success: true, txn_id, otp_code, message: "Transfer initiated" }); } catch (error) { res.status(500).json({ error: error.message }); } });
app.post("/validate-otp", async (req, res) => { try { const { txn_id, otp_code, receiver_phone } = req.body; if (!txn_id || !otp_code) return res.status(400).json({ error: "Missing fields" }); const { data: txn } = await supabase.from("transactions").select("*").eq("txn_id", txn_id).single(); if (!txn) return res.status(404).json({ error: "Txn not found" }); const { data: otp } = await supabase.from("otps").select("*").eq("txn_id", txn_id).single(); if (!otp || otp.used || otp.code !== otp_code) return res.status(400).json({ error: "Invalid OTP" }); await supabase.from("otps").update({ used: true, used_at: new Date() }).eq("id", otp.id); await supabase.from("transactions").update({ status: "ready_for_withdrawal" }).eq("txn_id", txn_id); await logAction("validated_otp", receiver_phone, { txn_id }); res.json({ success: true, txn_id, status: "ready_for_withdrawal", amount: txn.amount }); } catch (error) { res.status(500).json({ error: error.message }); } });
app.post("/atm-withdraw", async (req, res) => { try { const { txn_id, receiver_phone, otp_code, atm_location } = req.body; if (!txn_id) return res.status(400).json({ error: "Missing txn_id" }); const { data: txn } = await supabase.from("transactions").select("*").eq("txn_id", txn_id).single(); if (!txn || txn.status !== "ready_for_withdrawal") return res.status(400).json({ error: "Not ready" }); const { data: otp } = await supabase.from("otps").select("*").eq("txn_id", txn_id).single(); if (!otp || otp.code !== otp_code) return res.status(400).json({ error: "Invalid OTP" }); await supabase.from("transactions").update({ status: "withdrawn", completed_at: new Date() }).eq("txn_id", txn_id); await supabase.from("otps").update({ atm_location }).eq("id", otp.id); await logAction("atm_withdrawal", receiver_phone, { txn_id, amount: txn.amount }); res.json({ success: true, txn_id, status: "withdrawn", amount: txn.amount }); } catch (error) { res.status(500).json({ error: error.message }); } });
app.get("/transaction-status/:txn_id", async (req, res) => { try { const { data } = await supabase.from("transactions").select("*").eq("txn_id", req.params.txn_id).single(); if (!data) return res.status(404).json({ error: "Not found" }); res.json({ txn_id: data.txn_id, status: data.status, amount: data.amount, created_at: data.created_at }); } catch (error) { res.status(500).json({ error: error.message }); } });
app.get("/admin-logs", async (req, res) => { try { const { data } = await supabase.from("logs").select("*").order("created_at", { ascending: false }).limit(100); res.json({ total: data.length, logs: data }); } catch (error) { res.status(500).json({ error: error.message }); } });
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server on port " + PORT));
